server:
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: auth_user
    password: auth_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: ${JWT_SECRET:change-me-in-prod-please-use-a-long-random-string-min-32-chars}
    access-token-expiration-ms: 900000
    refresh-token-expiration-ms: 604800000
  frontend:
    confirm-url: http://localhost:5173/confirm

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: INFO
    com.netflix.discovery: OFF
